recipe: graph.v1

language: en

nlu_target: run_RegexMessageHandler

core_target: select_prediction

train_schema:
  nodes:
    schema_validator:
      needs:
        importer: __importer__
      uses: rasa.graph_components.validators.default_recipe_validator.DefaultV1RecipeValidator
      constructor_name: create
      fn: validate
      config: {}
      eager: false
      is_target: false
      is_input: true
      resource: null
    finetuning_validator:
      needs:
        importer: schema_validator
      uses: rasa.graph_components.validators.finetuning_validator.FinetuningValidator
      constructor_name: create
      fn: validate
      config:
        validate_core: true
        validate_nlu: true
      eager: false
      is_target: false
      is_input: true
      resource: null
    nlu_training_data_provider:
      needs:
        importer: finetuning_validator
      uses: rasa.graph_components.providers.nlu_training_data_provider.NLUTrainingDataProvider
      constructor_name: create
      fn: provide
      config:
        language: en
        persist: false
      eager: false
      is_target: false
      is_input: true
      resource: null
    domain_provider:
      needs:
        importer: finetuning_validator
      uses: rasa.graph_components.providers.domain_provider.DomainProvider
      constructor_name: create
      fn: provide_train
      config: { }
      eager: false
      is_target: true
      is_input: true
      resource: null
    domain_for_core_training_provider:
      needs:
        domain: domain_provider
      uses: rasa.graph_components.providers.domain_for_core_training_provider.DomainForCoreTrainingProvider
      constructor_name: create
      fn: provide
      config: { }
      eager: false
      is_target: false
      is_input: true
      resource: null
    story_graph_provider:
      needs:
        importer: finetuning_validator
      uses: rasa.graph_components.providers.story_graph_provider.StoryGraphProvider
      constructor_name: create
      fn: provide
      config:
        exclusion_percentage: null
      eager: false
      is_target: false
      is_input: true
      resource: null
    training_tracker_provider:
      needs:
        story_graph: story_graph_provider
        domain: domain_for_core_training_provider
      uses: rasa.graph_components.providers.training_tracker_provider.TrainingTrackerProvider
      constructor_name: create
      fn: provide
      config: { }
      eager: false
      is_target: false
      is_input: false
      resource: null
    run_WhitespaceTokenizer0:
      needs:
        training_data: nlu_training_data_provider
      uses: rasa.nlu.tokenizers.whitespace_tokenizer.WhitespaceTokenizer
      constructor_name: load
      fn: process_training_data
      config: {}
      eager: false
      is_target: false
      is_input: false
      resource: null
    train_RegexFeaturizer1:
      needs:
        training_data: run_WhitespaceTokenizer0
      uses: rasa.nlu.featurizers.sparse_featurizer.regex_featurizer.RegexFeaturizer
      constructor_name: create
      fn: train
      config: {}
      eager: false
      is_target: true
      is_input: false
      resource: null
    run_RegexFeaturizer1:
      needs:
        training_data: run_WhitespaceTokenizer0
        resource: train_RegexFeaturizer1
      uses: rasa.nlu.featurizers.sparse_featurizer.regex_featurizer.RegexFeaturizer
      constructor_name: load
      fn: process_training_data
      config: { }
      eager: false
      is_target: false
      is_input: false
      resource: null
    train_LexicalSyntacticFeaturizer2:
      needs:
        training_data: run_RegexFeaturizer1
      uses: rasa.nlu.featurizers.sparse_featurizer.lexical_syntactic_featurizer.LexicalSyntacticFeaturizer
      constructor_name: create
      fn: train
      config: {}
      eager: false
      is_target: true
      is_input: false
      resource: null
    run_LexicalSyntacticFeaturizer2:
      needs:
        training_data: run_RegexFeaturizer1
        resource: train_LexicalSyntacticFeaturizer2
      uses: rasa.nlu.featurizers.sparse_featurizer.lexical_syntactic_featurizer.LexicalSyntacticFeaturizer
      constructor_name: load
      fn: process_training_data
      config: { }
      eager: false
      is_target: false
      is_input: false
      resource: null
    train_CountVectorsFeaturizer3:
      needs:
        training_data: run_LexicalSyntacticFeaturizer2
      uses: rasa.nlu.featurizers.sparse_featurizer.count_vectors_featurizer.CountVectorsFeaturizer
      constructor_name: create
      fn: train
      config: {}
      eager: false
      is_target: true
      is_input: false
      resource: null
    run_CountVectorsFeaturizer3:
      needs:
        training_data: run_LexicalSyntacticFeaturizer2
        resource: train_CountVectorsFeaturizer3
      uses: rasa.nlu.featurizers.sparse_featurizer.count_vectors_featurizer.CountVectorsFeaturizer
      constructor_name: load
      fn: process_training_data
      config: { }
      eager: false
      is_target: false
      is_input: false
      resource: null
    train_CountVectorsFeaturizer4:
      needs:
        training_data: run_CountVectorsFeaturizer3
      uses: rasa.nlu.featurizers.sparse_featurizer.count_vectors_featurizer.CountVectorsFeaturizer
      constructor_name: create
      fn: train
      config:
        analyzer: char_wb
        min_ngram: 1
        max_ngram: 4
      eager: false
      is_target: true
      is_input: false
      resource: null
    run_CountVectorsFeaturizer4:
      needs:
        training_data: run_CountVectorsFeaturizer3
        resource: train_CountVectorsFeaturizer4
      uses: rasa.nlu.featurizers.sparse_featurizer.count_vectors_featurizer.CountVectorsFeaturizer
      constructor_name: load
      fn: process_training_data
      config:
        analyzer: char_wb
        min_ngram: 1
        max_ngram: 4
      eager: false
      is_target: false
      is_input: false
      resource: null
    train_CRF:
      needs:
        training_data: run_CountVectorsFeaturizer4
      uses: rasa.nlu.extractors.crf_entity_extractor.CRFEntityExtractor
      constructor_name: create
      fn: train
      config: {}
      eager: false
      is_target: true
      is_input: false
      resource: null
    train_selectiveDIET1:
      needs:
        training_data: run_CountVectorsFeaturizer4
      uses: "custom_components.selective_diet.SelectiveDIET"
      constructor_name: create
      fn: train
      config:
        epochs: 50
        intents_to_train: [ "transfer_money","pay_cc", "search_transactions","help", "check_earnings", "check_balance", "human_handoff" ]
        classifier_name: "global_router"
        entity_recognition: False
      eager: false
      is_target: true
      is_input: false
      resource: null
    train_selectiveDIET2:
      needs:
        training_data: run_CountVectorsFeaturizer4
      uses: "custom_components.selective_diet.SelectiveDIET"
      constructor_name: create
      fn: train
      config:
        epochs: 50
        intents_to_train: [ "transfer_money", "check_recipients", "inform", "ask_transfer_charge", "pay_cc", "search_transactions","help", "check_earnings", "check_balance", "human_handoff" ]
        classifier_name: "p2p_transfer"
        entity_recognition: False
      eager: false
      is_target: true
      is_input: false
      resource: null
    train_selectiveDIET3:
      needs:
        training_data: run_CountVectorsFeaturizer4
      uses: "custom_components.selective_diet.SelectiveDIET"
      constructor_name: create
      fn: train
      config:
        epochs: 50
        intents_to_train: [ "transfer_money", "pay_cc", "inform", "search_transactions","help", "check_earnings", "check_balance", "human_handoff" ]
        classifier_name: "pay_cc"
        entity_recognition: False
      eager: false
      is_target: true
      is_input: false
      resource: null
    train_selectiveDIET4:
      needs:
        training_data: run_CountVectorsFeaturizer4
      uses: "custom_components.selective_diet.SelectiveDIET"
      constructor_name: create
      fn: train
      config:
        epochs: 50
        intents_to_train: [ "transfer_money", "pay_cc", "inform", "search_transactions","help", "check_earnings", "check_balance", "human_handoff" ]
        classifier_name: "search_transactions"
        entity_recognition: False
      eager: false
      is_target: true
      is_input: false
      resource: null
    train_AugMemoizationPolicy0:
      needs:
        training_trackers: training_tracker_provider
        domain: domain_for_core_training_provider
      uses: rasa.core.policies.memoization.AugmentedMemoizationPolicy
      constructor_name: create
      fn: train
      config: { }
      eager: false
      is_target: true
      is_input: false
      resource: null
    train_RulePolicy1:
      needs:
        training_trackers: training_tracker_provider
        domain: domain_for_core_training_provider
      uses: rasa.core.policies.rule_policy.RulePolicy
      constructor_name: create
      fn: train
      config:
        core_fallback_threshold: 0.4
        core_fallback_action_name: "action_default_fallback"
        enable_fallback_prediction: True
      eager: false
      is_target: true
      is_input: false
      resource: null
    train_TEDPolicy3:
      needs:
        training_trackers: training_tracker_provider
        domain: domain_for_core_training_provider
      uses: rasa.core.policies.ted_policy.TEDPolicy
      constructor_name: create
      fn: train
      config:
        epochs: 40
      eager: false
      is_target: true
      is_input: false
      resource: null

predict_schema:
  nodes:
    domain_provider:
      needs: { }
      uses: rasa.graph_components.providers.domain_provider.DomainProvider
      constructor_name: load
      fn: provide_inference
      config: { }
      eager: true
      is_target: false
      is_input: false
      resource:
        name: domain_provider
    nlu_message_converter:
      needs:
        messages: __message__
      uses: rasa.graph_components.converters.nlu_message_converter.NLUMessageConverter
      constructor_name: load
      fn: convert_user_message
      config: { }
      eager: true
      is_target: false
      is_input: false
      resource: null
    run_WhitespaceTokenizer0:
      needs:
        messages: nlu_message_converter
      uses: rasa.nlu.tokenizers.whitespace_tokenizer.WhitespaceTokenizer
      constructor_name: load
      fn: process
      config: { }
      eager: true
      is_target: false
      is_input: false
      resource: null
    run_RegexFeaturizer1:
      needs:
        messages: run_WhitespaceTokenizer0
      uses: rasa.nlu.featurizers.sparse_featurizer.regex_featurizer.RegexFeaturizer
      constructor_name: load
      fn: process
      config: { }
      eager: true
      is_target: false
      is_input: false
      resource:
        name: train_RegexFeaturizer1
    run_LexicalSyntacticFeaturizer2:
      needs:
        messages: run_RegexFeaturizer1
      uses: rasa.nlu.featurizers.sparse_featurizer.lexical_syntactic_featurizer.LexicalSyntacticFeaturizer
      constructor_name: load
      fn: process
      config: { }
      eager: true
      is_target: false
      is_input: false
      resource:
        name: train_LexicalSyntacticFeaturizer2
    run_CountVectorsFeaturizer3:
      needs:
        messages: run_LexicalSyntacticFeaturizer2
      uses: rasa.nlu.featurizers.sparse_featurizer.count_vectors_featurizer.CountVectorsFeaturizer
      constructor_name: load
      fn: process
      config: { }
      eager: true
      is_target: false
      is_input: false
      resource:
        name: train_CountVectorsFeaturizer3
    run_CountVectorsFeaturizer4:
      needs:
        messages: run_CountVectorsFeaturizer3
      uses: rasa.nlu.featurizers.sparse_featurizer.count_vectors_featurizer.CountVectorsFeaturizer
      constructor_name: load
      fn: process
      config:
        analyzer: char_wb
        min_ngram: 1
        max_ngram: 4
      eager: true
      is_target: false
      is_input: false
      resource:
        name: train_CountVectorsFeaturizer4
    run_CRF:
      needs:
        messages: run_CountVectorsFeaturizer4
      uses: rasa.nlu.extractors.crf_entity_extractor.CRFEntityExtractor
      constructor_name: load
      fn: process
      config: { }
      eager: true
      is_target: false
      is_input: false
      resource:
        name: train_CRF
    run_selectiveDIET1:
      needs:
        messages: run_CRF
      uses: "custom_components.selective_diet.SelectiveDIET"
      constructor_name: load
      fn: process
      config:
        epochs: 50
        intents_to_train: [ "transfer_money","pay_cc", "search_transactions","help", "check_earnings", "check_balance", "human_handoff" ]
        classifier_name: "global_router"
        entity_recognition: False
      eager: true
      is_target: false
      is_input: false
      resource:
        name: train_selectiveDIET1
    run_selectiveDIET2:
      needs:
        messages: run_selectiveDIET1
      uses: "custom_components.selective_diet.SelectiveDIET"
      constructor_name: load
      fn: process
      config:
        epochs: 50
        intents_to_train: [ "transfer_money", "check_recipients", "inform", "ask_transfer_charge", "pay_cc", "search_transactions","help", "check_earnings", "check_balance", "human_handoff" ]
        classifier_name: "p2p_transfer"
        entity_recognition: False
      eager: true
      is_target: false
      is_input: false
      resource:
        name: train_selectiveDIET2
    run_selectiveDIET3:
      needs:
        messages: run_selectiveDIET2
      uses: "custom_components.selective_diet.SelectiveDIET"
      constructor_name: load
      fn: process
      config:
        epochs: 50
        intents_to_train: [ "transfer_money", "pay_cc", "inform", "search_transactions","help", "check_earnings", "check_balance", "human_handoff" ]
        classifier_name: "pay_cc"
        entity_recognition: False
      eager: true
      is_target: false
      is_input: false
      resource:
        name: train_selectiveDIET3
    run_selectiveDIET4:
      needs:
        messages: run_selectiveDIET3
      uses: "custom_components.selective_diet.SelectiveDIET"
      constructor_name: load
      fn: process
      config:
        epochs: 50
        intents_to_train: [ "transfer_money", "pay_cc", "inform", "search_transactions","help", "check_earnings", "check_balance", "human_handoff" ]
        classifier_name: "search_transactions"
        entity_recognition: False
      eager: true
      is_target: false
      is_input: false
      resource:
        name: train_selectiveDIET4
    run_intent_resolver:
      needs:
        messages: run_selectiveDIET4
        tracker: __tracker__
      uses: "custom_components.intent_resolver.IntentResolver"
      constructor_name: load
      fn: process
      config:
        global_router_name: "global_router"
        skills:
          p2p_transfer:
            start_intent: transfer_money
            end_action: action_transfer_money
          pay_cc:
            start_intent: pay_cc
            end_action: action_pay_cc
          search_transactions:
            start_intent: search_transactions
            end_action: action_transaction_search
      eager: true
      is_target: false
      is_input: false
      resource: null
    run_fallback:
      needs:
        messages: run_intent_resolver
      uses: rasa.nlu.classifiers.fallback_classifier.FallbackClassifier
      constructor_name: load
      fn: process
      config:
        threshold: 0.7
      eager: true
      is_target: false
      is_input: false
      resource: null
    run_RegexMessageHandler:
      needs:
        messages: run_intent_resolver
      uses: rasa.nlu.classifiers.regex_message_handler.RegexMessageHandler
      constructor_name: load
      fn: process
      config: { }
      eager: true
      is_target: false
      is_input: false
      resource: null
    run_AugMemoizationPolicy0:
      needs:
        domain: domain_provider
        rule_only_data: rule_only_data_provider
        tracker: __tracker__
      uses: rasa.core.policies.memoization.AugmentedMemoizationPolicy
      constructor_name: load
      fn: predict_action_probabilities
      config: { }
      eager: true
      is_target: false
      is_input: false
      resource:
        name: train_AugMemoizationPolicy0
    run_RulePolicy1:
      needs:
        domain: domain_provider
        rule_only_data: rule_only_data_provider
        tracker: __tracker__
      uses: rasa.core.policies.rule_policy.RulePolicy
      constructor_name: load
      fn: predict_action_probabilities
      config:
        core_fallback_threshold: 0.4
        core_fallback_action_name: "action_default_fallback"
        enable_fallback_prediction: True
      eager: true
      is_target: false
      is_input: false
      resource:
        name: train_RulePolicy1
    run_TEDPolicy3:
      needs:
        domain: domain_provider
        rule_only_data: rule_only_data_provider
        tracker: __tracker__
      uses: rasa.core.policies.ted_policy.TEDPolicy
      constructor_name: load
      fn: predict_action_probabilities
      config:
        epochs: 40
      eager: true
      is_target: false
      is_input: false
      resource:
        name: train_TEDPolicy3
    rule_only_data_provider:
      needs: { }
      uses: rasa.graph_components.providers.rule_only_provider.RuleOnlyDataProvider
      constructor_name: load
      fn: provide
      config: { }
      eager: true
      is_target: false
      is_input: false
      resource:
        name: train_RulePolicy1
    select_prediction:
      needs:
        policy0: run_AugMemoizationPolicy0
        policy1: run_RulePolicy1
        policy3: run_TEDPolicy3
        domain: domain_provider
        tracker: __tracker__
      uses: rasa.core.policies.ensemble.DefaultPolicyPredictionEnsemble
      constructor_name: load
      fn: combine_predictions_from_kwargs
      config: { }
      eager: true
      is_target: false
      is_input: false
      resource: null
